### ISSUE TITLE
Not species specific  - but only for some genuses?

### ISSUE THREAD

**Issue by biolars** [cypamigon/inat_downloader#2]
I am experiencing a weird thing when trying to download bear photos. Although I specify either "Ursus arctos" or "Ursus maritimus" in my species.csv, I get a mixture in the results folder and metadata file.

A similar thing did not happen when I downloaded wolf "Canis lupus arctos" images (I did not get any dogs "Canis familiaris").

Cheers,
Lars

**Comment by cypamigon** [comment]
With the iNaturalist API (that the script relies on), the results you are getting are the same than the one you would get using the website. 

For example, when searching for "Ursus maritimus" with the search tool on the website. You will have two results: "Polar Bear" and "Eurasian Brown Bear", because this one is also called "Ursus maritimus tyrannus" :

![Result_iNaturalist_Website](https://github.com/cypamigon/inat_downloader/assets/116843639/08f05fe2-4d6d-4a01-9438-f6bb69ed6d87)

When using the script and specifying "Ursus maritimus" in species.csv, it will behave the same : your results will contain both "Polar Bear" **AND** "Eurasian Brown Bear". 

However, there are workarounds to filter for only the desired species. One approach is to try using alternative names for the species in the website's search tool to see if it retrieves only that specific species. If it does, you can use that name in the species.csv file and rerun the script.

For instance, instead of "Ursus maritimus" you could use "Ursus maritimus marinus", this one give a single result : 

![Result_2_iNaturalist_Website](https://github.com/cypamigon/inat_downloader/assets/116843639/f9ec88db-6f5f-4589-9ac9-540d519e4976)

**Comment by biolars** [comment]
Ahh I did not realise that is would also use seemingly abandoned names!
[](https://www.inaturalist.org/taxa/147154-Ursus-arctos-arctos)
![image](https://github.com/cypamigon/inat_downloader/assets/128479878/91c6dfdb-aacb-4264-aeff-d996c2a430e4)
